server:
    port: 8082 # Change for each microservice

spring:
    application:
        name: user-service # Unique service name

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
